

export const data = [
   {
      title: 'Асинхронный JavaScript 1',
      description: 'Обсуждение асинхронного JavaScript: почему это так важно, как эта возможность языка может использована для обработки потенциальных блокирующих операций, как, например получение данных с сервера.',
      image: '/posts/javascript/logo.png',
      created_date: '01.012022',
      author: 'shandyrov askar',
      post: '/posts/javascript/intro-1',
      url: 'intro-1',   
   },
   {
      title: 'Введение в объекты JavaScript 2',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.012022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты JavaScript 3',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.012022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты JavaScript 4',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.012022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты JavaScript 5',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.012022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты JavaScript 6',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.012022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты JavaScript 7',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.012022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты JavaScript 8',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.012022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты JavaScript 9',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.012022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты JavaScript 10',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.012022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты JavaScript 11',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.012022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты JavaScript 12',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.012022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты JavaScript 13',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.012022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты JavaScript 14',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.012022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты JavaScript 15',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.012022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты JavaScript 16',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.012022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты JavaScript 17',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.012022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты JavaScript 18 ',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.012022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
         {
      title: 'Введение в объекты JavaScript 19',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.012022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты JavaScript 20',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.012022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
]; 