

export const data = [
   {
      title: 'Введение в React',
      description: 'React — свободная реляционная система управления базами данных. Разработку и поддержку MySQL осуществляет корпорация Oracle, получившая права на торговую марку вместе с поглощённой Sun Microsystems, которая ранее приобрела шведскую компанию php AB.',
      image: '/posts/react/logo.png',
      created_date: '24.04.2022',
      author: 'shandyrov askar',
      post: '/posts/react/intro-1',
      url: 'intro-1',   
   },
   {
      title: 'Введение в объекты React 2',
      description: 'Объектно-ориентированная природа react важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/react/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/react/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты React 3',
      description: 'Объектно-ориентированная природа react важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/react/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/react/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты React 4',
      description: 'Объектно-ориентированная природа react важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/react/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/react/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты React 5',
      description: 'Объектно-ориентированная природа react важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/react/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/react/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты React 6',
      description: 'Объектно-ориентированная природа react важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/react/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/react/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты React 7',
      description: 'Объектно-ориентированная природа react важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/react/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/react/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты React',
      description: 'Объектно-ориентированная природа react важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/react/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/react/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты React',
      description: 'Объектно-ориентированная природа react важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/react/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/react/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты React',
      description: 'Объектно-ориентированная природа react важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/php/logo.png',
      created_date: '02.01.2022',
      author: 'shahandyrov askar',
      post: '/posts/php/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты React',
      description: 'Объектно-ориентированная природа react важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/react/logo.png',
      created_date: '02.01.2022',
      author: 'shahandyrov askar',
      post: '/posts/react/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты React',
      description: 'Объектно-ориентированная природа react важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/react/logo.png',
      created_date: '02.01.2022',
      author: 'shandyrov askar',
      post: '/posts/react/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты React',
      description: 'Объектно-ориентированная природа php важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/php/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/php/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты React',
      description: 'Объектно-ориентированная природа react важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/react/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/react/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты React',
      description: 'Объектно-ориентированная природа react важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/react/logo.png',
      created_date: '02.01/2022',
      author: 'shahandyrov askar',
      post: '/posts/react/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты React',
      description: 'Объектно-ориентированная природа react важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/react/logo.png',
      created_date: '02.01.2022',
      author: 'shahandyrov askar',
      post: '/posts/react/intro-2',
      url: 'intro-2',
   },
]; 
