

export const data = [
   {
      title: 'Введение в kubernetes',
      description: 'MySQL — свободная реляционная система управления базами данных. Разработку и поддержку MySQL осуществляет корпорация Oracle, получившая права на торговую марку вместе с поглощённой Sun Microsystems, которая ранее приобрела шведскую компанию MySQL AB.',
      image: '/posts/mysql/logo.png',
      created_date: '03.02.2022',
      author: 'shandyrov askar',
      post: '/posts/mysql/intro-1',
      url: 'intro-1',   
   },
   {
      title: 'Введение в объекты kubernetes 2',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/mysql/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/mysql/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты kubernetes 3',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/mysql/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/mysql/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты kubernetes 4',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/mysql/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/mysql/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты kubernetes 5',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/kubernetes/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты kubernetes 6',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/kubernetes/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/mysql/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты kubernetes 7',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/kubernetes/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/mysql/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты kubernetes 8',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/kubernetes/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/mysql/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты kubernetes 9',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/kubernetes/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/mysql/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты kubernetes 10',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/kubernetes/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/mysql/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты kubernetes 11',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/kubernetes/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/kubernetes/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты kubernetes 12',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/kubernetes/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/kubernetes/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты kubernetes 13',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/kubernetes/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/kubernetes/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты kubernetes 14',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/kubernetes/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/kubernetes/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты kubernetes 15',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/kubernetes/logo.png',
      created_date: '02.01/2022',
      author: 'shahandyrov askar',
      post: '/posts/kubernetes/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты kubernetes 16',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/kubernetes/logo.png',
      created_date: '02.01.2022',
      author: 'shahandyrov askar',
      post: '/posts/kubernetes/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты kubernetes 17',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/kubernetes/logo.png',
      created_date: '02.01.2022',
      author: 'shahandyrov askar',
      post: '/posts/kubernetes/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты kubernetes 18 ',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/kubernetes/logo.png',
      created_date: '04.10.2021',
      author: 'shahandyrov askar',
      post: '/posts/kubernetes/intro-2',
      url: 'intro-2',
   },
         {
      title: 'Введение в объекты kubernetes 19',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/kubernetes/logo.png',
      created_date: '02.01.2022',
      author: 'shahandyrov askar',
      post: '/posts/kubernetes/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты kubernetes 20',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '03.10.2000',
      author: 'shahandyrov askar',
      post: '/posts/kubernetes/intro-2',
      url: 'intro-2',
   },
]; 
