

export const data = [
   {
      title: 'Введение в Docker',
      description: 'Docker — это открытая платформа для разработки, доставки и запуска приложений. Docker позволяет вам отделить ваши приложения от вашей инфраструктуры, чтобы вы могли быстро доставлять программное обеспечение. С помощью Docker вы можете управлять своей инфраструктурой так же, как вы управляете своими приложениями. Воспользовавшись методологиями Docker для быстрой доставки, тестирования и развертывания кода, вы можете значительно сократить задержку между написанием кода и его запуском в производственной среде.',
      image: '/posts/docker/logo.png',
      created_date: '03.06.2022',
      author: 'shandyrov askar',
      post: '/posts/javascript/intro-1',
      url: 'intro-1',   
   },
   {
      title: 'Docker Введение в объекты Docker 2',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты Docker 3',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты Docker 4',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты Docker 5',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты Docker 6',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты Docker 7',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты Docker 8',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты Docker 9',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты Docker 10',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты Docker 11',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты Docker 12',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты Docker 13',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты Docker 14',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты Docker 15',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.01/2022',
      author: 'shahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты Docker 16',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.01.2022',
      author: 'shahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты Docker 17',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.01.2022',
      author: 'shahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты JavaScript 18 ',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '04.10.2021',
      author: 'shahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
         {
      title: 'Введение в объекты Docker 19',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '04.01.2022',
      author: 'shahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты JavaScript 20',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '03.10.2000',
      author: 'shahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
]; 