

export const data = [
   {
      title: 'Введение в php',
      description: 'php — свободная реляционная система управления базами данных. Разработку и поддержку MySQL осуществляет корпорация Oracle, получившая права на торговую марку вместе с поглощённой Sun Microsystems, которая ранее приобрела шведскую компанию php AB.',
      image: '/posts/mysql/logo.png',
      created_date: '24.04.2022',
      author: 'shandyrov askar',
      post: '/posts/mysql/intro-1',
      url: 'intro-1',   
   },
   {
      title: 'Введение в объекты php 2',
      description: 'Объектно-ориентированная природа php важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/mysql/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/mysql/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты php 3',
      description: 'Объектно-ориентированная природа php важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/mysql/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/mysql/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты php 4',
      description: 'Объектно-ориентированная природа php важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/mysql/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/mysql/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты MySQL 5',
      description: 'Объектно-ориентированная природа php важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/mysql/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты php 6',
      description: 'Объектно-ориентированная природа php важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/mysql/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/mysql/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты php 7',
      description: 'Объектно-ориентированная природа php важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/mysql/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/mysql/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты php 8',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/mysql/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/mysql/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты php 9',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/mysql/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/mysql/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты php 10',
      description: 'Объектно-ориентированная природа php важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/php/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/php/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты php 11',
      description: 'Объектно-ориентированная природа php важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/php/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/php/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты php 12',
      description: 'Объектно-ориентированная природа php важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/php/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/php/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты php 13',
      description: 'Объектно-ориентированная природа php важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/php/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/php/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты php 14',
      description: 'Объектно-ориентированная природа php важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/php/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/php/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты php 15',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/php/logo.png',
      created_date: '02.01/2022',
      author: 'shahandyrov askar',
      post: '/posts/php/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты php 16',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/php/logo.png',
      created_date: '02.01.2022',
      author: 'shahandyrov askar',
      post: '/posts/php/intro-2',
      url: 'intro-2',
   },
]; 
