

export const data = [
   {
      title: 'Введение в MySQL',
      description: '',
      image: '/posts/mysql/logo.png',
      created_date: '03.10.2021',
      author: 'shandyrov askar',
      post: '/posts/mysql/intro-1',
      url: 'intro-1',   
   },
   {
      title: 'Введение в объекты MySQL 2',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/mysql/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/mysql/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты MySQL 3',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/mysql/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/mysql/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты MySQL 4',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/mysql/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/mysql/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты MySQL 5',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/mysql/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты MySQL 6',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/mysql/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/mysql/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты MySQL 7',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/mysql/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/mysql/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты MySQL 8',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/mysql/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/mysql/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты MySQL 9',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/mysql/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/mysql/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты MySQL 10',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/mysql/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/mysql/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты MySQL 11',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/mysql/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/mysql/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты MySQL 12',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/mysql/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/mysql/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты MySQL 13',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/mysql/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/mysql/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты MySQL 14',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/mysql/logo.png',
      created_date: '02.01.2022',
      author: 'ahandyrov askar',
      post: '/posts/mysql/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты MySQL 15',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/mysql/logo.png',
      created_date: '02.01/2022',
      author: 'shahandyrov askar',
      post: '/posts/mysql/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты MySQL 16',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/mysql/logo.png',
      created_date: '02.01.2022',
      author: 'shahandyrov askar',
      post: '/posts/mysql/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты MySQL 17',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.01.2022',
      author: 'shahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты MySQL 18 ',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '04.10.2021',
      author: 'shahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
         {
      title: 'Введение в объекты MySQL 19',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '02.01.2022',
      author: 'shahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
      {
      title: 'Введение в объекты MySQL 20',
      description: 'Объектно-ориентированная природа JavaScript важна для понимания, если вы хотите углубить знание языка и писать более эффективный код. Поэтому мы подготовили модуль, который поможет вам в этом.',
      image: '/posts/javascript/logo.png',
      created_date: '03.10.2000',
      author: 'shahandyrov askar',
      post: '/posts/javascript/intro-2',
      url: 'intro-2',
   },
]; 
